### ISSUE TITLE
TXs rate limiting by intercepting API calls to IRI (API proxy)

### ISSUE THREAD

**Issue by CWarner818** [iota-tangle-io/spamalot-project#1]
Proxy commands to allow spamming only when node is idle, as well as pull metrics like # of connected clients, # of transactions sent, etc

**Comment by CWarner818** [comment]
Just testing. I guess we should use issues to allow for commenting

**Comment by luca-moser** [comment]
possible ways to achieve this:
* use nginx with http://nginx.org/en/docs/http/ngx_http_mirror_module.html to mirror requests to the slave (you would proxy to IRI and to the slave)
* back-in a proxy into the slave

**Comment by CWarner818** [comment]
This issue was moved to iota-tangle-io/iota-spamalot.go#3
