### ISSUE TITLE
Slave config parameters

### ISSUE THREAD

**Issue by luca-moser** [iota-tangle-io/spamalot-project#2]
Parameters which can be set for the spammers:
* depth
* mwm (minimal weight magnitude)
* node address (included port; i.e. `http://iota-tangle.io:14265`)
* tag
* message
* PoW mode (local or remote by node)
* cooldown time between txs

The configuration is sent down to the slave through the chosen transport.

**Comment by CWarner818** [comment]
This issue was moved to iota-tangle-io/iota-spamalot.go#2
